- src/main/java/com/devillage/teamproject/controller/post/PostController.java
- src/main/java/com/devillage/teamproject/controller/post/PostControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/entity/Bookmark.java
- src/main/java/com/devillage/teamproject/entity/Category.java
- src/main/java/com/devillage/teamproject/entity/User.java
- src/main/java/com/devillage/teamproject/exception/ExceptionCode.java
- src/main/java/com/devillage/teamproject/service/post/PostService.java
- src/main/java/com/devillage/teamproject/service/post/PostServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/post/PostControllerTest.java
- src/test/java/com/devillage/teamproject/repository/post/PostRepositoryTest.java
- src/test/java/com/devillage/teamproject/repository/user/UserRepositoryTest.java
- src/test/java/com/devillage/teamproject/service/post/PostServiceImplTest.java
> POST posts/{post-id}/bookmark

- src/main/java/com/devillage/teamproject/controller/user/UserController.java
- src/main/java/com/devillage/teamproject/controller/user/UserControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/MultiResponseDto.java
- src/main/java/com/devillage/teamproject/dto/PageInfo.java
- src/main/java/com/devillage/teamproject/dto/SingleResponseDto.java
- src/main/java/com/devillage/teamproject/dto/UserDto.java
- src/main/java/com/devillage/teamproject/service/user/UserService.java
- src/main/java/com/devillage/teamproject/service/user/UserServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/user/UserControllerTest.java
- src/test/java/com/devillage/teamproject/service/user/UserServiceTest.java
> GET /profile/{user-id}

- src/main/java/com/devillage/teamproject/controller/post/PostController.java
- src/main/java/com/devillage/teamproject/controller/post/PostControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/entity/Like.java
- src/main/java/com/devillage/teamproject/entity/Post.java
- src/main/java/com/devillage/teamproject/entity/ReportedPost.java
- src/main/java/com/devillage/teamproject/entity/User.java
- src/main/java/com/devillage/teamproject/exception/ExceptionCode.java
- src/main/java/com/devillage/teamproject/repository/post/BookmarkRepository.java
- src/main/java/com/devillage/teamproject/repository/post/LikeRepository.java
- src/main/java/com/devillage/teamproject/repository/post/ReportedPostRepository.java
- src/main/java/com/devillage/teamproject/service/post/PostService.java
- src/main/java/com/devillage/teamproject/service/post/PostServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/post/PostControllerTest.java
- src/test/java/com/devillage/teamproject/service/post/BookmarkTest.java
- src/test/java/com/devillage/teamproject/service/post/LikeTest.java
- src/test/java/com/devillage/teamproject/service/post/PostServiceTest.java
- src/test/java/com/devillage/teamproject/service/post/ReportTest.java
> POST /posts/{post-id}/report & /posts/{post-id}/like

- src/main/java/com/devillage/teamproject/security/util/JwtTokenUtil.java
RefreshToken 구현과 함께 PR하려고 했으나 예상보다 너무 오래 걸리고 걸림돌이 많아서..
여러분의 코드 완성을 위한 JwtTokenUtil만 미리 올립니다.
(단, 실제 작동을 확인하시려면 아직 제가 PR하지 않은 다른 코드들이 필요합니다 ㅜㅜ)
> JwtTokenUtil

- src/main/java/com/devillage/teamproject/controller/post/PostController.java
- src/main/java/com/devillage/teamproject/controller/post/PostControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/FileDto.java
- src/main/java/com/devillage/teamproject/dto/MultiResponseDto.java
- src/main/java/com/devillage/teamproject/dto/PageInfo.java
- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/dto/TagDto.java
- src/main/java/com/devillage/teamproject/entity/Post.java
- src/main/java/com/devillage/teamproject/exception/ExceptionCode.java
- src/main/java/com/devillage/teamproject/repository/post/PostRepository.java
- src/main/java/com/devillage/teamproject/service/post/PostService.java
- src/main/java/com/devillage/teamproject/service/post/PostServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/post/PostControllerTest.java
- src/test/java/com/devillage/teamproject/repository/post/PostRepositoryTest.java
- src/test/java/com/devillage/teamproject/service/post/BookmarkTest.java
- src/test/java/com/devillage/teamproject/service/post/GetPostsTest.java
- src/test/java/com/devillage/teamproject/service/post/LikeTest.java
- src/test/java/com/devillage/teamproject/service/post/PostServiceTest.java
- src/test/java/com/devillage/teamproject/service/post/ReportTest.java
> GET /posts?category={category}&page={page}&size={size}

- src/main/java/com/devillage/teamproject/controller/post/PostController.java
- src/main/java/com/devillage/teamproject/controller/post/PostControllerImpl.java
- src/main/java/com/devillage/teamproject/service/post/PostService.java
- src/main/java/com/devillage/teamproject/service/post/PostServiceImpl.java
- src/test/java/com/devillage/teamproject/service/post/BookmarkTest.java
- src/test/java/com/devillage/teamproject/service/post/LikeTest.java
- src/test/java/com/devillage/teamproject/service/post/PostServiceTest.java
- src/test/java/com/devillage/teamproject/service/post/ReportTest.java
수정 후 PostControllerTest에서 아래 에러가 발생했는데 아직 해결하지 못했습니다.
```
Failed to load ApplicationContext
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'postControllerImpl' defined in file [C:\Users\...\Devillage\build\classes\java\main\com\devillage\teamproject\controller\post\PostControllerImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.devillage.teamproject.security.util.JwtTokenUtil' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
Caused by: …
```
> POST /posts/{post-id}/(bookmark & report & like) JWT 적용입니다.

- src/main/java/com/devillage/teamproject/controller/user/UserController.java
- src/main/java/com/devillage/teamproject/controller/user/UserControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/UserDto.java
- src/main/java/com/devillage/teamproject/entity/Block.java
- src/main/java/com/devillage/teamproject/entity/User.java
- src/main/java/com/devillage/teamproject/repository/user/BlockRepository.java
- src/main/java/com/devillage/teamproject/service/user/UserService.java
- src/main/java/com/devillage/teamproject/service/user/UserServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/user/UserControllerTest.java
- src/test/java/com/devillage/teamproject/repository/user/UserRepositoryTest.java
- src/test/java/com/devillage/teamproject/service/user/UserServiceTest.java
> POST /users/block/{user-id}

- src/main/java/com/devillage/teamproject/controller/user/UserController.java
- src/main/java/com/devillage/teamproject/controller/user/UserControllerImpl.java
- src/main/java/com/devillage/teamproject/entity/User.java
- src/main/java/com/devillage/teamproject/exception/ExceptionCode.java
- src/main/java/com/devillage/teamproject/service/user/UserService.java
- src/main/java/com/devillage/teamproject/service/user/UserServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/user/UserControllerTest.java
- src/test/java/com/devillage/teamproject/service/user/UserServiceTest.java
회원탈퇴, 프로필 조회를 토큰요청식으로 바꿨습니다.
그리고 UserService에 findVerifiedUser를 새로 만들었는데,
null체크와 함께 탈퇴한 회원인지도 확인합니다.
다만, 그냥 추가하는게 아니라 IDE리팩토링 툴로 findUser() -> findVerifiedUser() 하고 findUser()를 새로생성하는 식으로 했으면
모든 부분에서 빠짐없이 변경이 잘됐을텐데 라는 아쉬움이 좀 남습니다.
> 몇몇 요청형식 변경 및 리팩토링

- src/main/java/com/devillage/teamproject/controller/comment/CommentController.java
- src/main/java/com/devillage/teamproject/controller/comment/CommentControllerImpl.java
- src/main/java/com/devillage/teamproject/entity/ReComment.java
- src/main/java/com/devillage/teamproject/exception/ExceptionCode.java
- src/main/java/com/devillage/teamproject/repository/comment/ReCommentRepository.java
- src/main/java/com/devillage/teamproject/service/comment/CommentService.java
- src/main/java/com/devillage/teamproject/service/comment/CommentServiceImpl.java
- src/main/java/com/devillage/teamproject/service/post/PostServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/comment/CommentControllerTest.java
- src/test/java/com/devillage/teamproject/controller/post/GetPostsControllerTest.java
- src/test/java/com/devillage/teamproject/controller/post/PostControllerTest.java
- src/test/java/com/devillage/teamproject/repository/comment/ReCommentRepositoryTest.java
- src/test/java/com/devillage/teamproject/service/comment/CommentServiceImplTest.java
- src/test/java/com/devillage/teamproject/service/post/BookmarkTest.java
- src/test/java/com/devillage/teamproject/service/post/GetPostsServiceTest.java
- src/test/java/com/devillage/teamproject/service/post/LikeTest.java
- src/test/java/com/devillage/teamproject/service/post/PostServiceTest.java
- src/test/java/com/devillage/teamproject/service/post/ReportTest.java
> DELETE ReComment 삭제 /posts/{post-id}/comments/{comment-id}/{re-comment-id}

- build.gradle
- src/main/java/com/devillage/teamproject/controller/comment/CommentController.java
- src/main/java/com/devillage/teamproject/controller/comment/CommentControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/CommentDto.java
- src/main/java/com/devillage/teamproject/entity/Comment.java
- src/main/java/com/devillage/teamproject/entity/Post.java
- src/main/java/com/devillage/teamproject/entity/User.java
- src/main/java/com/devillage/teamproject/service/comment/CommentService.java
- src/main/java/com/devillage/teamproject/service/comment/CommentServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/comment/CommentControllerTest.java
- src/test/java/com/devillage/teamproject/service/comment/CommentServiceTest.java
- src/test/java/com/devillage/teamproject/util/TestConstants.java
> POST 코맨트 작성 /posts/{post-id}/comments

- src/main/java/com/devillage/teamproject/controller/post/PostController.java
- src/main/java/com/devillage/teamproject/controller/post/PostControllerImpl.java
- src/main/java/com/devillage/teamproject/entity/AuditingEntity.java
- src/main/java/com/devillage/teamproject/entity/Post.java
- src/main/java/com/devillage/teamproject/repository/post/PostRepository.java
- src/main/java/com/devillage/teamproject/service/post/PostService.java
- src/main/java/com/devillage/teamproject/service/post/PostServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/post/GetPostsControllerTest.java
- src/test/java/com/devillage/teamproject/repository/post/PostRepositoryTest.java
> GET 검색어 조회 /posts/search?page={page}&size={size}

- src/main/java/com/devillage/teamproject/controller/comment/CommentController.java
- src/main/java/com/devillage/teamproject/controller/comment/CommentControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/CommentDto.java
- src/main/java/com/devillage/teamproject/entity/Comment.java
- src/main/java/com/devillage/teamproject/entity/ReComment.java
- src/main/java/com/devillage/teamproject/service/comment/CommentService.java
- src/main/java/com/devillage/teamproject/service/comment/CommentServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/comment/CommentControllerTest.java
- src/test/java/com/devillage/teamproject/service/comment/CommentServiceTest.java
> PATCH /posts/{post-id}/comments/{comment-id} & PATCH /posts/{post-id}/comments/{comment-id}/{re-comment-id}

- src/main/java/com/devillage/teamproject/security/config/SecurityConfig.java
- src/main/java/com/devillage/teamproject/security/util/JwtTokenUtil.java
허용된 요청 외에 모두 차단하는 것으로 변경되었습니다.
> 서버 배포를 위한 시큐리티 설정 변경

- src/test/java/com/devillage/teamproject/controller/comment/CommentControllerTest.java
- src/test/java/com/devillage/teamproject/controller/post/GetPostsControllerTest.java
- src/test/java/com/devillage/teamproject/controller/post/PostControllerTest.java
- src/test/java/com/devillage/teamproject/controller/user/UserControllerTest.java
- src/test/java/com/devillage/teamproject/service/comment/CommentServiceTest.java
- src/test/java/com/devillage/teamproject/service/post/PostServiceTest.java
> Feat : 테스트 에러해결 최신화

- src/main/java/com/devillage/teamproject/controller/comment/CommentController.java
- src/main/java/com/devillage/teamproject/controller/comment/CommentControllerImpl.java
- src/main/java/com/devillage/teamproject/controller/post/PostController.java
- src/main/java/com/devillage/teamproject/controller/post/PostControllerImpl.java
- src/main/java/com/devillage/teamproject/controller/user/UserController.java
- src/main/java/com/devillage/teamproject/controller/user/UserControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/entity/Comment.java
- src/main/java/com/devillage/teamproject/entity/CommentLike.java
- src/main/java/com/devillage/teamproject/entity/User.java
- src/main/java/com/devillage/teamproject/exception/ExceptionCode.java
- src/main/java/com/devillage/teamproject/repository/comment/CommentLikeRepository.java
- src/main/java/com/devillage/teamproject/service/comment/CommentService.java
- src/main/java/com/devillage/teamproject/service/comment/CommentServiceImpl.java
- src/main/java/com/devillage/teamproject/service/post/PostService.java
- src/main/java/com/devillage/teamproject/service/post/PostServiceImpl.java
- src/main/java/com/devillage/teamproject/service/user/UserService.java
- src/main/java/com/devillage/teamproject/service/user/UserServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/comment/CommentControllerTest.java
- src/test/java/com/devillage/teamproject/controller/user/UserControllerTest.java
- src/test/java/com/devillage/teamproject/service/comment/CommentServiceTest.java
- src/test/java/com/devillage/teamproject/service/user/UserServiceTest.java
일단 원복부터 pr하고 나머지 완료안된 부분은 따로 pr하겠습니다.
> Fix: 잘못된 머지로 인한 원복 작업

- src/main/java/com/devillage/teamproject/controller/exception/ErrorResponse.java
- src/main/java/com/devillage/teamproject/controller/exception/ExceptionController.java
좀 더 사용성이 좋도록 개선하였습니다. log를 추가한건 에러의 정확한 발생위치를 파악하기 위해서 입니다.
> Refactor : ErrorResponse 개선

- src/main/java/com/devillage/teamproject/controller/post/PostController.java
- src/main/java/com/devillage/teamproject/controller/post/PostControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/service/post/PostService.java
- src/main/java/com/devillage/teamproject/service/post/PostServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/post/PostControllerTest.java
- src/test/java/com/devillage/teamproject/service/post/PostServiceTest.java
> GET/posts/{post-id} 수정

- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/entity/Category.java
- src/main/java/com/devillage/teamproject/entity/Post.java
- src/test/java/com/devillage/teamproject/controller/post/PostControllerTest.java
- src/test/java/com/devillage/teamproject/service/post/PostServiceTest.java
PostServiceTest,PostControllerTest > savePost()
둘 다 같은 맥락으로 객체를 조회하지 못하고 있는 것 같습니다.
> test 오류 원인 확인용 임시 PR

- src/main/java/com/devillage/teamproject/controller/post/PostController.java
- src/main/java/com/devillage/teamproject/controller/post/PostControllerImpl.java
- src/main/java/com/devillage/teamproject/controller/user/UserController.java
- src/main/java/com/devillage/teamproject/controller/user/UserControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/dto/UserDto.java
- src/main/java/com/devillage/teamproject/entity/Post.java
- src/main/java/com/devillage/teamproject/service/user/UserService.java
- src/main/java/com/devillage/teamproject/service/user/UserServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/post/PostControllerTest.java
- src/test/java/com/devillage/teamproject/controller/user/UserControllerTest.java
- src/test/java/com/devillage/teamproject/service/post/PostServiceTest.java
게시글 내용 일부를 리턴하는 response를 postId 리턴으로 변경하였습니다.
(게시글 수정의 경우 당장은 문제가 없겠으나 실제 운영 에러 발생 시, 이슈 트래킹이 어려울 것 같긴한데 그 외 목적으로 게시글 내용을 리턴하는건 불필요하니 등록과 동일하게 response 변경하였습니다.)
> Test: savePost,editPost test 수정(+Response 값 변경)

- build.gradle
- src/docs/asciidoc/index.adoc
- src/main/java/com/devillage/teamproject/security/config/SecurityConfig.java
- src/main/resources/static/docs/index.html
머지되면 이슈에 올릴 예정인데 누락된 테스트나 일부 구현되지 않은 메소드들이 있습니다.
작업하다가 수정이 필요해보이는 부분도 사견을 덧붙이긴했습니다.
다만 우선순위는 어떻게 해야될지는 모르겠네요.
> Rest docs 추가

- src/test/java/com/devillage/teamproject/controller/post/PostControllerTest.java
> Test: PostControllerTest 수정

- src/main/java/com/devillage/teamproject/controller/post/PostController.java
- src/main/java/com/devillage/teamproject/controller/post/PostControllerImpl.java
- src/main/java/com/devillage/teamproject/exception/ExceptionCode.java
- src/main/java/com/devillage/teamproject/repository/posttag/PostTagRepository.java
- src/main/java/com/devillage/teamproject/service/post/PostService.java
- src/main/java/com/devillage/teamproject/service/post/PostServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/post/GetPostsControllerTest.java
- src/test/java/com/devillage/teamproject/repository/post/PostRepositoryTest.java
- src/test/java/com/devillage/teamproject/repository/post/TagRepositoryTest.java
- src/test/java/com/devillage/teamproject/service/post/GetPostsServiceTest.java
- src/test/java/com/devillage/teamproject/service/post/LikeTest.java
- src/test/java/com/devillage/teamproject/util/TestConstants.java
> getPostsByCategory 모든 카테고리 조회 로직 추가 & getPostsByTag 로직 작성

- src/main/java/com/devillage/teamproject/controller/comment/CommentController.java
- src/main/java/com/devillage/teamproject/controller/comment/CommentControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/CommentDto.java
- src/main/java/com/devillage/teamproject/entity/Comment.java
- src/main/java/com/devillage/teamproject/entity/ReComment.java
- src/main/java/com/devillage/teamproject/entity/ReCommentLike.java
- src/main/java/com/devillage/teamproject/service/comment/CommentServiceImpl.java
- src/test/java/com/devillage/teamproject/controller/comment/CommentControllerTest.java
게시글 조회시 댓글 포함은 이 PR에 들어있지 않습니다
> 댓글 조회 시 좋아요 여부 포함

- src/main/java/com/devillage/teamproject/controller/comment/CommentController.java
> Fix : 댓글 작성시 내용이 반영안되는 버그 수정

- src/main/java/com/devillage/teamproject/dto/CommentDto.java
- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/dto/ReportDto.java
- src/main/java/com/devillage/teamproject/dto/UserDto.java
기왕하는 김에 다른분들 것 까지 했습니다. 다들 한번 보시고 이상하거나 누락된 부분이 있으면 수정해주세요.
> Feat : Dto에 validation추가

- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/entity/Post.java
**중요 : 혼동의 여지가 있는 일부 필드명을 수정하였으니 참고바랍니다.
> 게시글에 좋아요와 북마크 여부 표시

- src/main/java/com/devillage/teamproject/controller/comment/CommentController.java
- src/main/java/com/devillage/teamproject/controller/comment/CommentControllerImpl.java
- src/main/java/com/devillage/teamproject/dto/PostDto.java
- src/main/java/com/devillage/teamproject/entity/Comment.java
- src/main/java/com/devillage/teamproject/entity/Post.java
- src/main/java/com/devillage/teamproject/repository/comment/CommentLikeRepository.java
- src/main/java/com/devillage/teamproject/service/comment/CommentService.java
- src/main/java/com/devillage/teamproject/service/comment/CommentServiceImpl.java
- src/test/java/com/devillage/teamproject/service/comment/CommentServiceTest.java
> Fix: commentLike 좋아요 카운트 안되는 문제 수정

- src/main/java/com/devillage/teamproject/config/WebSocketConfig.java
- src/main/java/com/devillage/teamproject/controller/chat/MessageController.java
- src/main/java/com/devillage/teamproject/security/config/SecurityConfig.java
- src/main/java/com/devillage/teamproject/service/chat/MessageServiceImpl.java
- src/test/java/com/devillage/teamproject/service/chat/ChatServiceTest.java
- src/test/java/com/devillage/teamproject/service/chat/MessageServiceTest.java
\+ MessageService > joinUserChatRoom 수정
> Refactor: 소켓 통신 엔드포인트 수정

- src/main/java/com/devillage/teamproject/config/WebConfig.java
- src/main/java/com/devillage/teamproject/config/WebSocketEventListener.java
> Fix : 채팅이 정상적으로 연결되지 않던 문제 수정

- .gitignore
- build.gradle
- src/main/java/com/devillage/teamproject/config/AwsS3Config.java
- src/main/java/com/devillage/teamproject/entity/File.java
- src/main/java/com/devillage/teamproject/service/file/LocalImageService.java
- src/main/java/com/devillage/teamproject/service/file/S3ImageService.java
- src/main/resources/application.yml
인터페이스상의 변화는 없습니다.
다만 특정 yml파일이 업데이트 되기전까지는 에러가 나기 때문에 별도 브랜치로 pr합니다.
> Feat : s3 이미지 제공 기능
